[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "npm"]

[phases.install]
cmds = ["cd frontend && npm install", "pip install -r requirements.txt"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd server && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
